# Example Project Entry
# Projects are standalone applications and utilities built for/with OpenCode.
# These are complete apps, not extensions.
# Place actual entries in: data/projects/your-project-name.yaml

# ============================================================================
# REQUIRED FIELDS
# ============================================================================

name: Example OpenCode Dashboard
repo: https://github.com/example/opencode-dashboard
tagline: Web-based dashboard for monitoring OpenCode sessions
description: |
  A standalone web application for monitoring and managing
  OpenCode sessions across multiple projects.
  
  Features:
  - Real-time session monitoring
  - Token usage analytics
  - Multi-project overview

# ============================================================================
# OPTIONAL FIELDS
# ============================================================================

# Scope is often not relevant for standalone projects
# Include only if the project can be installed globally vs per-project

tags:
  - dashboard
  - monitoring
  - web-ui
  - analytics

min_version: "1.0.0"

homepage: https://example.com/opencode-dashboard

installation: |
  ## Prerequisites
  - Node.js 18+
  - OpenCode 1.0.0 or later

  ## Installation
  ```bash
  # Clone the repository
  git clone https://github.com/example/opencode-dashboard
  cd opencode-dashboard

  # Install dependencies
  npm install

  # Start the dashboard
  npm start
  ```

  ## Configuration
  Create a `.env` file:
  ```bash
  OPENCODE_LOG_DIR=~/.config/opencode/logs
  PORT=3000
  ```

  ## Usage
  Open `http://localhost:3000` in your browser.

  ## Docker (Alternative)
  ```bash
  docker run -p 3000:3000 \
    -v ~/.config/opencode:/opencode:ro \
    example/opencode-dashboard
  ```
